name: Publish to Website

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Build tar.gz package from source
      run: |
        EA_VERSION=$(node -p -e "require('./package.json').version")
        EA_NAME="extensiveautomation"
        rm -rf .git/
        rm -rf .github/
        cd ..
        tar -zcvf ${EA_NAME}-webclient-${EA_VERSION}.tar.gz ${EA_NAME}-webclient/
    - name: Upload to Website
      run: |
        EA_VERSION=$(node -p -e "require('./package.json').version")
        EA_NAME="extensiveautomation"
        sudo apt-get install sshpass
        touch RELEASE_WEBCLIENT_DATE
        touch RELEASE_WEBCLIENT_VERSION
        echo ${EA_VERSION} > RELEASE_WEBCLIENT_VERSION
        date +'%F' > RELEASE_WEBCLIENT_DATE
        export SSHPASS=${{ secrets.WEBSITE_PASSWORD }}
        sshpass -e scp -P 9443 -o StrictHostKeyChecking=no RELEASE_WEBCLIENT_* ${{ secrets.WEBSITE_LOGIN }}@${EA_NAME}.org:/home/upload_versions
        sshpass -e scp -P 9443 -o StrictHostKeyChecking=no  ../${EA_NAME}-webclient-${EA_VERSION}.tar.gz ${{ secrets.WEBSITE_LOGIN }}@${EA_NAME}.org:/home/upload/webclient